default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: rails_ecommerce_api_development

test:
  <<: *default
  database: rails_ecommerce_api_test

production:
  <<: *default
  database: rails_ecommerce_api_production
  username: <%= ENV['ECOMMERCE_API_DATABASE_USERNAME'] %>
  password: <%= ENV['ECOMMERCE_API_DATABASE_PASSWORD'] %>
